### ISSUE TITLE
Save For Multiple Lists

### ISSUE THREAD

**Issue by babalou** [justingit/dada-mail#544]
Hi Justin,

I'v just upgraded to the new DM 9.1.0 PRO, in CGI mode, on my company server (Apache 2.4.18, PHP 5.5.31, MySQL 5.5.42, PERL 5.10.1). When I log into a mailing list with the root account, I don't see the the button labeled "Save For Multiple Lists". Where is this button ?

Best.

**Comment by justingit** [comment]
Please look at the changelog for notes on how it would work: 

To use this feature, log into a mailing list with your Dada Root Password, otherwise the feature will not be available. Look for the button labeled, Save For Multiple Lists.... When clicked, a modal window will open allowing you to select the mailing lists that you would like to save the list settings for that list control panel to. 

By default, all the available mailing lists are selected, but you may customize this if you would like.

**Comment by justingit** [comment]
Closing this, because of lack of feedback on the directions. I'm guessing it's working?

**Comment by babalou** [comment]
Hi Justin,

In fact, due to the tracker plugin issue, I moved back to DM 9.0.2 Pro, but I will upgrade to the 9.1.1 version this week and I will test again the "Save For Multiple Lists" feature.
