### ISSUE TITLE
Can't locate object method "new" via package "CGI::File::Temp"

### ISSUE THREAD

**Issue by zwerfkat** [justingit/dada-mail#595]
Installed latest version 9.6.0 08/02/16 .

When I try to uplad a file to add subscribers, I get:

Can't locate object method "new" via package "CGI::File::Temp" at (eval 28) line 66, <CONFIG> line 1.
Compilation failed in require at /xxxx/cgi-bin/dada//DADA/App.pm line 49, <CONFIG> line 1.
BEGIN failed--compilation aborted at /xxxx/cgi-bin/dada//DADA/App.pm line 49, <CONFIG> line 1.
Compilation failed in require at mail.cgi line 16, <CONFIG> line 1.
BEGIN failed--compilation aborted at mail.cgi line 16, <CONFIG> line 1.

While cpan gives me: CGI::File::Temp is up to date (4.35).
apache error file:  Premature end of script headers: mail.cgi
perl -version: This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi

What is going wrong?

**Comment by zwerfkat** [comment]
nobody?

**Comment by zwerfkat** [comment]
figured it out: removed file DADA/perllib/CGI/File/Temp.pm and now it will use Temp.pm from my default Perl installation which has function new(). But this shouldn't happen of course with the perllib from DADA, or?

**Comment by justingit** [comment]
Not sure. It could be a different version of some module that's conflicting with what's shipped in Dada Mail. I don't know what the solution is, unless you rely on either the system's Perl library, or Dada Mail's

I've recently made a bundle of every CPAN module uses: 

https://metacpan.org/pod/Bundle::DadaMailXXL

So that you can easily install every CPAN module require to run Dada Mail. That will at least have the effect of making sure these modules are available and up to date on a system-level. 

I at least want to say that the Perl modules will be looked for first in the site wide library locations, before looking in Dada Mail's own perllib.
