### ISSUE TITLE
DadaMail not working on Mobile devices!

### ISSUE THREAD

**Issue by jbhs** [justingit/dada-mail#643]
On my (iPad in the Browser Safari or Chrome and on my Moblie in Chrome) the Sidepane-Menu is closing on touch, It also seems the Menu is not dark like it should be. In the moment you touch on the menu the menu becomes dark for a second and moves away to the left side.

v10.4.0 Stable

**Comment by jbhs** [comment]
This still happens with v10.5.0 Stable

**Comment by holzhannes** [comment]
I did some more tests. It seems this only happens on the **Send a Message** and **Send a Webpage** Screen, the problem is the `<a class="exit-off-canvas"></a>` wich is over the hole page.
The exit-off-canvas links is not directly behind the section it should be like this:`</section><a class="exit-off-canvas"></a></div>` but on the affected sites it is `</section></div><a class="exit-off-canvas"></a>`. This is causing the Problem.

**Comment by holzhannes** [comment]
Can confirm Commit https://github.com/justingit/dada-mail/commit/e388e4fd5b2ed3c7a5ab87bff171acc74f7d81b7 is solving Issue #643. 
Thank you very much 😃 .
