### ISSUE TITLE
Error :- Your IP Address has changed

### ISSUE THREAD

**Issue by amitsquare** [justingit/dada-mail#661]
Hi Guys ,

System was working fine , suddenly i am getting this error whenever i am login on my panel .
Attaching screen shot as well .

<img width="477" alt="screen shot 2017-04-17 at 2 00 48 pm" src="https://cloud.githubusercontent.com/assets/7547850/25083786/a1990fe2-2376-11e7-9a88-0a623a3fc541.png">

Do let know the reason which might be causing this error .

**Comment by justingit** [comment]
If you're IP *is* changing, your login will fail, as checking matching IP addresses is part of the sessioning system. You can disable this via the Dada Mail installer, 

http://dadamailproject.com/d/install_dada_mail-advanced_configuration.pod.html#Check-for-Matching-IP-Addresses

**Comment by derekllaw** [comment]
I just started getting that error as well. The proposed solution is a non-starter, as it is difficult to change the configuration when the problem prevents me from logging in.

**Comment by justingit** [comment]
@derekllaw, the instructions do describe a way to make the changes without having to log in.

**Comment by derekllaw** [comment]
Hardly. The link you pointed to says "check this option" but doesn't give the name of the variable or explain that the fix requires editing a configuration file.
I have found that the error is only appearing in Chrome, so I suspect it is related to their recent enforcement of HTTPS, but I'm not sure exactly what.

**Comment by justingit** [comment]
Here's instructions on how to drop back into the installer without the need to log into a list, beforehand, 

http://dadamailproject.com/d/install_dada_mail.pod.html#Making-Additional-Global-Configuration-Changes-using-the-Dada-Mail-Installer

If you would like to do this manually, you'll want to set the following in the .dada_config file: 

 $CP_SESSION_PARAMS = { 
	check_matching_ip_addresses => 0,
 };

(rather than, "1")

I do suggest letting the installer handle that for you, though, as any errors in the .dada_config file will disallow the app from working.

**Comment by derekllaw** [comment]
Thanks, that's a very comprehensive answer.
