### ISSUE TITLE
"Recent Activity" screen still uses dada.txt log file, rather than, "dada_consent_activity" table

### ISSUE THREAD

**Issue by sandy-j** [justingit/dada-mail#733]
Hi Justin,
I've upgraded to 11.0.1 for GDPR reasons, and I notice that subscriptions and unsubscriptions are no longer being logged, although I still see "Subscription Confirmation Sent" messages in the log. This is making the Recent Activity feature less useful. Is this working as designed? Have I missed an option somewhere? 
TIA
Sandy

**Comment by justingit** [comment]
Hello Sandy, 

Subscriptions and Unsubscriptions ARE being logged, just in a database table called, **dada_consent_activity** rather than being logged in the **dada.txt** log file. We've moved away from placing this information in the dada.txt file for a few reasons: 

* This log file gets HUGE
* This log file held Personally Identifying Information (PII), since the email address and ip address for this data (and other data) was being saved. There's no real great way to manage this data (remember, the log file gets HUGE), so it's better to save this in the database, which has a to of built-in tools to better manage this amount of data. 

You're right though, the "Recent Activity" screen in the list control panel relied on the data being logged in the dada.txt file, and v11 of Dada Mail does not log subscriptions/unsubscriptions in this log file anymore.  

We'll port the code that works with the "Recent Activity" screen from the dada.txt log file to the new database table in a future release of Dada Mail. I'll leave this issue open, as it is def. an issue.

**Comment by sandy-j** [comment]
Justin,
Thank you for explaining this, I understand the reasons for the change, and now that I know about it I'm quite satisfied that all is WAD. 
Sandy
