### ISSUE TITLE
Version 11.2.6 - Can't add an image to an email

### ISSUE THREAD

**Issue by anysongsuz** [justingit/dada-mail#785]
Version 11.2.6 - Can't add an image to an email - I've recently upgraded the software to version 11.2.6 and I can upload an image, but I cannot select and add an image to the email.  The image popup window will not go away and there is no button to close it.  I have to hit the previous arrow on the browser to go back to the previous screen.

![image](https://user-images.githubusercontent.com/45327500/48976973-8a1fe580-f056-11e8-9970-e348b2d0e3c4.png)
I would appreciate your assistance with this as soon as possible.  Thank you!
Suzie

**Comment by anysongsuz** [comment]
Would appreciate any help with this.  My client sends out notifications often and cannot insert graphics with this version.  Help!

**Comment by justingit** [comment]
I'm closing this, just because this is not a support forum. My suggestion though, is to use one of the two other alternative file managers that are bundled with Dada Mail. You're using the KCFinder, which is the oldest. Try the Rich Filemanager, which is the current default. If that doesn't work, try the Core 5 Filemanager. 

If you need additional support, start a new ZenDesk ticket ,

https://dadamailproject.com/contact/

Cheers,

**Comment by anysongsuz** [comment]
Thanks for responding, Justin.  How do I switch to Rich Filemanager?  I’m just using what came with the latest version of Dadamail.  

 

 

Sincerely,

 

Suzie Schulenberg

(615) 403-2837

 <mailto:suzie@faverwebs.com> suzie@faverwebs.com

 <http://www.faverwebs.com/> www.FaverWebs.com

**Comment by justingit** [comment]
Please start a new thread using Zendesk, I've closed this issue here. 

Switching file managers is done during install/upgrade in the installer itself. You would want to drop back into the installer, to make the configuration changes.
