### ISSUE TITLE
Sending: Options - saving SMTP settings that include a password fail when, "Save for Multiple Lists" is used

### ISSUE THREAD

**Issue by justingit** [justingit/dada-mail#793]
This problem is mostly caused by how the SMTP password is saved per-list, as the password itself is encrypted, but the "key" (not quite the correct term) that's used to do the encryption is different for each list. 

My guess is that the key for the list you're logged in from is used for every list, so can never then be decrypted. 

This issue is most likely ALSO an issue for anywhere a encrypted piece of information is saved in the list settings, AND the option to save for multiple lists is present. D'oh. 

It's also perhaps a conversation/deep dive to have, in coming to an opinion on if this information needs to be encrypted at all? If someone has control of the backend, they would also have control of resetting this password anyways. 

For the moment, it's probably easier to keep things encrypted, and leave that issue for another day, and just fix the bug as stated.

**Comment by rspilk** [comment]
I have a lot of lists to populate credentials for and most of them have invalid passwords (this is tested by going and selecting "save then test") and they fail authentication.

Are you saying the hashed value shown in the password field from the API could be applied to other lists or that it wouldn't be the same because it was hashed with a different salt?

Just wondering how I can quickly apply these passwords to all of our lists short of browsing through each one manually

**Comment by justingit** [comment]
If working correctly, the password SHOULD be saved in the DB as a different string for each list, as the encrypted password is saved using different paramaters. Even if the decrypted password is the same.

**Comment by justingit** [comment]
Just as an FYI, @rspilk this bug should be fixed in the v11.2.8 release of Dada Mail,
