### ISSUE TITLE
Problem fetching URL: "css/app.css" Whenever an email is sent out with a theme's template applied

### ISSUE THREAD

**Issue by dickmo** [justingit/dada-mail#852]
New error in log never seen before. 11-4-6   When a subscriber clicks on the unsubscribe verification screen this error shows up.  Also when the admin approves the unsubscribe it shows up again.   Using mailing list options 
 Require the subscriber to click a link/button to confirm unsubscription .
It does seem to work even with the displayed error 

Problem fetching URL:
$VAR1 = {
          'url' => bless( [
                            bless( do{\(my $o = 'css/app.css')}, 'URI::_generic' ),
                            undef
                          ], 'URI::URL' ),
          'message' => 'URL must be absolute',
          'status_line' => '400 URL must be absolute',
          'code' => 400
        };
 at DADA/App/MyMIMELiteHTML.pm line 341.

**Comment by justingit** [comment]
Looking into this, this will happen any time an email message is sent out that's wrapped on one of the templates of an email theme. The app is trying to resolve the css in this line in the template: 

`<link rel="stylesheet" type="text/css" href="css/app.css">`

Since it's relative, it'll always fail. 

This problem has been for a while, but the error reporting has recently been made more verbose, so the reporting in the error log is much more obvious.

**Comment by dickmo** [comment]
It is safe to say it is not serious or is there something I could do to 
eliminate it?
I am using the default template nothing fancy at all.



Richard Mourino

------ Original Message ------

**Comment by justingit** [comment]
It's pretty harmless - I did fix the problem, and the commit is logged, if you want to patch this manually yourself - I'll have the change in then next release. 

I appreciate the report.
