### ISSUE TITLE
Plain text messages end up with unwanted formatting

### ISSUE THREAD

**Issue by RayGX** [justingit/dada-mail#899]
Entering a message in the Plain Text Version tab with following plain text paragraph layout:
1. some stuff...
some stuff...

2. some stuff...
some stuff...

3. some stuff...
1. some stuff...
2. some stuff...
3. some stuff...
4. some stuff...

Nothing is entered using HTML Version tab.
With HTML Version tab selected, "Do not send an HTML version (only PlainText version)" is selected.

If message is sent with the above settings, the resulting message body is formatted as:
1. some stuff...
some stuff...

1. some stuff...
some stuff...

1. some stuff...
1. some stuff...
2. some stuff...
3. some stuff...
4. some stuff...

Somehow the text is being reformatted and the paragraphs renumbered even though send plain text version only was selected.

RayDDCox

**Comment by RayGX** [comment]
OK...even GitHub is reformatting my message so it isn't clear what DADA is doing.  Please see the attached txt file to hopefully see what is happening.
[DADA_GitHub.txt](https://github.com/justingit/dada-mail/files/4221747/DADA_GitHub.txt)

**Comment by RayGX** [comment]
Sorry...closed by accident!

**Comment by justingit** [comment]
My guess is that the final email is still in HTML - Dada Mail will send in HTML and in PlainText by default. If plaintext is the only source, the HTML version will be made from that, and will be run through the MarkDown engine to pick up any formatting, which is what you're seeing. 

If you simply do not want an HTML version of the message, just uncheck the option, 

[ ]  Convert PlainText-only mass email messages to HTML 

In, Mass Mailing: Options

Doing so will send your message exactly like you have typed it. 

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/39739/74782765-546daa80-5261-11ea-8f72-7570243a7de5.png">

**Comment by RayGX** [comment]
I did select the “send plain text only” option and still got the unwanted formatting when viewing the supposedly plain text in Outlook.  Outlook can be configured to view all messages in plain text but I can’t find anything stating that it will attempt to format plain text messages if they are not being viewed in plain text mode.

**Comment by justingit** [comment]
> I did select the “send plain text only” option and still got the unwanted formatting when viewing the supposedly plain text in Outlook. 

Can you be a little more specific? There is no option in Dada Mail labeled, "send plain text only" 

In the Draft screen there is an option in the HTML tab: 
**Do not send an HTML version (only PlainText version)** 

In the Mass Mailing: Options screen there is an option labeled, 
 **Convert PlainText-only mass email messages to HTML** 

As I wrote in my og reply, you'll want to uncheck the latter. If not, you'll actually be sending an HTML message with your PlainText; the HTML being created from the Plaintext version, once run through the Markdown renderer. The changing in the numbered bulletpoints is due to the Markdown engine interpreting your PlainText message. Github makes the same changes, as it itself supports Markdown.

**Comment by RayGX** [comment]
OK...I was referring to the option you mentioned in the HTML tab of the Draft screen.

When I deselected the option you mentioned in the Mass Mailing screen the issue was resolved so I will consider this issue closed.

Thanks for the help!
