### ISSUE TITLE
Database Error on Insert to Profile_fields   record  on occasion 

### ISSUE THREAD

**Issue by dickmo** [justingit/dada-mail#912]
This happens ever so often but not all the time.    
DBD::mysql::st execute failed: Duplicate entry 'xxxxxxxx1@gmail.com' for key 'email' at DADA/Profile/Fields/baseSQL.pm line 126.
problems updating fields with geo ip data: cannot do statement (at insert)! Duplicate entry 'xxxxxxxx1@gmail.com' for key 'email'
 at DADA/Logging/Clickthrough/baseSQL.pm line 506.
 at DADA/Logging/Clickthrough/baseSQL.pm line 778.

We used it as a newsletter for our club so every member is defined with their names in the additional profile fields .
Also on occasion the added fields in the profile_fields get wiped out.

**Comment by justingit** [comment]
> This happens ever so often but not all the time.

Can you document a workflow where this does happen all the time? 

>  Also on occasion the added fields in the profile_fields get wiped out.

Can you open a separate issue for this?

**Comment by dickmo** [comment]
It has been 2 weeks   and only 1 errors.

Cannot see a pattern so for now   close this





Richard Mourino

------ Original Message ------

**Comment by dickmo** [comment]
I think I found a pattern.  The Profile email address (in database) is in lower case but on the very few items that loose their values in the profile fields  the email coming in is in mixed case where the first character is Upper case.  Example   Subscriber email is john@email.com  but the tracking comes in as John@email.com First letter is capital.

**Comment by justingit** [comment]
Great insight, I'll investigate.

**Comment by justingit** [comment]
Hmm, I still am having trouble finding a way where one can enter a mixed cased email address so that it shows up in any of the databases that deal with profile data, and thus: I cant recreate the bug, unless I add it in perhaps manually. 

How did a mixed-case email address get added to the database to begin with? (as a spitball question)

**Comment by dickmo** [comment]
FYI  We use it for our club.
So I added in our members with a csv file   their email (in lower case)  
and their names (in the optional profile fields)
So Profile table has lower case  Profile Fields table  also has lower 
case with optional  data (first last name)

We sent out mass mailing  and when a particular members opened up the 
email and the tracking code executed.
I found that their real email address had a capital first letter and the 
values in the optional profile fields  where  blank.

  I found in the profile field table an entry with Cap first letter email 
address the rest of the data was blank
  There was another entry same email but lower case  (the one I entered 
with the csv file).

  The only data I found in the Profile table was lower case

  In Basesql.pm  around line 114  you do an insert into the profile_field 
table could this be the place
that you insert the values from tracker but it has the Cap letter in it 
?
Some vendors allow you to replace your real email address with an alias 
so the alias is used in certain conditions
and maybe the tracker is picking that up.
I will track this particular member and see if it happens again.



Richard Mourino

------ Original Message ------

**Comment by justingit** [comment]
Yeah, I can't track down when that capital letter is added. What I will do is try to normalize the case a bit better throughout the Profile system, and hope I squash it. 

It's a sticky one, since I dont wanna keep this issue open forever, but feel not so great about closing it (but I'm gunna close it after I do that work). 

If it does happen again, feel free to open up a new issue and I'll apply some more work with it.

**Comment by dickmo** [comment]
Ok

When I program in sql is always do a compare in same case       if  
lcase(field1) = lcase(field2)
or insert Lcase(field1)     if I want it always to be lower.

But I think the issue is that I have it as lower case and this member 
has mixed case in their email address.
If I am able to re verify this again I will let you know using the #912 
number.

Looks like I have 3 members that have it this way.
Thanks for looking.

Richard Mourino



------ Original Message ------

**Comment by justingit** [comment]
Email case is set in the Dada Mail app itself, since technically, email addresses are case SENSITIVE (if one can believe that). But by default, all email addresses are transformed to lowercase. 

Is it possible that an email address was added either outside of Dada Mail to the database directly using mixed case, and that's what's mucking things up?

**Comment by dickmo** [comment]
Double checked   all of the email addresses in datamail are lower case.

Tried to re produced   failed.  Using gmail  created an account with mix 
case but it changed it.
The member that it happened was using aol  I will try aol next time

This is a random issue from somewhere so I will close it  I will keep 
looking to try and
find a better pattern.
Thanks for looking
I will close issue





Richard Mourino

------ Original Message ------
